version: '3.5'

services:
  susswebservice:
    image: susswebservice
    container_name: "susswebservice"
    restart: always
    build:
      context: .
      dockerfile: deployments/webservice/Dockerfile
    expose:
      - 5000
    ports:
      - "5000:5000"
    environment:
      - MODE=${MODE}
      - SERVER_API_PASSWORD=${SERVER_API_PASSWORD}
      - SERVER_API_KEY=${SERVER_API_KEY}