# Maximum non-suspicious speed of movement (in MPH) e.g. 500 Mile per Hour
SUSPICIOUS_THRESHOLD: 500
# Detection mode either Optimistic, Normal or Pessimistic
# Optimistic:   will deduct accuracy radius from distance
# Normal:       ignore accuracy radius
# Pessimistic:  will add accuracy radius to distance
DETECTION_MODE: "Optimistic"
GEO_CITY_DB: GeoLite2-City.mmdb
WEBSERVICE:
  PORT: 443
  DOMAIN: example.com
  ENABLE_AUTOCERT: true
DB:
  GORM_LOG_LEVEL: error